server:
  port: 8080
  servlet:
    context-path: /api/mp-booking/v1

spring:
  datasource:
    url: jdbc:postgresql://zgd-db-dev:5432/zgd-dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

