server:
  port: 8080
  servlet:
    context-path: /api/mp-booking/v1

spring:
  datasource:
    url: jdbc:postgresql://zorgundostu-db:5432/zorgundostu
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/zorgundostu
    user: postgres
    password: postgres
    baseline-on-migrate: true
