server:
  port: 8090
  servlet:
    context-path: /api/mp-booking/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
