server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zorgundostu
    username: postgres
    password: 123123a
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/zorgundostu
    user: postgres
    password: 123123a
    baseline-on-migrate: true
