server:
  port: 8080
  servlet:
    context-path: /api/mp-booking/v1

spring:
  datasource:
    url: jdbc:postgresql://ce-db-dev:5432/ce-dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

endpoints:
  integration:
    shelter: "http://localhost:8092/api/ce-integration/v1/integrations/shelters"
    notification: "http://localhost:8092/api/ce-integration/v1/integrations/notifications"

openapi:
  app:
    title: "Shelter API"
    description: "This project includes shelter operations"
    version: 1.0
    contact : "Contact Support"
    email: "tuncay@talls.tech"
    licence: "Shelter 1.0"
    url: "https://www.talls.tech"